version: 0.2

phases:
  install:
    commands:
      - echo INSTALLING ECS_CLI
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - ecs-cli -v
      - ecs-cli configure --cluster $cluster_name --default-launch-type FARGATE --region $aws_default_region --config-name $config_name
      - ecs-cli configure profile --profile-name $profile_name --access-key $aws_access_key_id --secret-key $aws_secret_access_key
      - DATETIME=$(date +%d%m%y__%H%M)
      - VERSION="$(git log --pretty=format:'%h' -n 1) $(date +%d:%m:%Y*****%H:%M)"
      - echo $VERSION
      - echo CONFIGURING ECS-CLI
      - echo lets see one last time !!!!!!!YES

  pre_build:
    commands:
      - echo Logging.. in to Amazon ECR ....
      - eval $(aws ecr get-login --region $aws_default_region --no-include-email)
  build:
    commands:
#      - make django-run
      # - docker build -t cybsafe/phishtray:latest -f prod.Dockerfile .
      # - docker tag cybsafe/phishtray:latest $aws_account_id.dkr.ecr.eu-west-2.amazonaws.com/phishtray/django:newlatest
      # - docker push $aws_account_id.dkr.ecr.eu-west-2.amazonaws.com/phishtray/django:newlatest
  post_build:
    commands:
#FOR EC2 LAUNCH TYPE
     # - cd ./docker/prod
     # - ecs-cli compose --project-name demo-django-compose --file docker-compose.yml --ecs-params ecs-params.yml --region $aws_default_region create --launch-type EC2
     # - ecs-cli compose up --region $aws_default_region --cluster Dev-Phishtray-101 --launch-type EC2

#FOR FARGATE

     - ecs-cli compose --project-name demo-django-compose-FARGATE --file docker-compose.yml --ecs-params ecs-paramsFARGATE.yml --region $aws_default_region create --launch-type FARGATE
     - ecs-cli compose up --region $aws_default_region --cluster Dev-Phishtray-101 --launch-type FARGATE
