version: '3'

services:

  phishtray_db:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray/db:latest
    volumes:
    - /var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-FG-Phishtray
        awslogs-region: eu-west-2
        awslogs-stream-prefix: ecs

  phishtray_apps:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray/django:latest
    ports:
    - "9000:9000"
    environment:
    - DATABASE_HOST=phishtray_db
    networks:
    - webnet
    depends_on:
    - phishtray_db
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-FG-Phishtray
        awslogs-region: eu-west-2
        awslogs-stream-prefix: ecs

networks:
  webnet:
