# Generated by Django 2.0.5 on 2018-09-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, max_length=25, null=True)),
                ('department_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('default_language', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('week_starts', models.CharField(blank=True, max_length=3, null=True)),
                ('module_email_time', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_contact', models.CharField(blank=True, max_length=25, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=200, null=True)),
                ('reset_date', models.DateTimeField(blank=True, null=True)),
                ('invite_date', models.DateField(blank=True, null=True)),
                ('invite_sent', models.IntegerField()),
                ('can_annotate', models.IntegerField(blank=True, null=True)),
                ('is_remote_only', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
                ('is_dummy', models.IntegerField(blank=True, null=True)),
                ('is_trial', models.IntegerField(blank=True, null=True)),
                ('is_beta', models.IntegerField()),
                ('requires_daily_reset', models.IntegerField(blank=True, null=True)),
                ('requires_attn', models.IntegerField(blank=True, null=True)),
                ('course_complete', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email_update', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
